### ISSUE TITLE
MultipleAdmits

### ISSUE THREAD

**Issue by pandaorb** [cookjohns/HospitalDatabase#16]
There are a handful of patients who are being re-admitted without ever being discharged.

**Comment by acm0055** [comment]
Do you have test code to test this? @pandaorb

**Comment by pandaorb** [comment]
The query shows all occupied rooms and the patients who are in them. It's only showing entries with no discharge date.

SELECT occupiedRooms.roomNumber AS roomNumber, 
	occupiedRooms.firstName AS firstName, 
	occupiedRooms.lastName AS lastName, 
	a.timeAdmitted AS timeAdmitted
	FROM Admits a 
		JOIN (
			SELECT pr.roomNumber, currentPatients.patientId, currentPatients.firstName, currentPatients.lastName
			FROM PatientRoom pr
				JOIN (
					SELECT p.patientId, p.firstName, p.lastName
					FROM Patient p LEFT JOIN Discharges d ON p.patientId = d.patientId WHERE d.date IS NULL) currentPatients
				ON pr.patientId = currentPatients.patientId) occupiedRooms
		ON a.patientId = occupiedRooms.patientId
	ORDER BY occupiedRooms.roomNumber, a.timeAdmitted;
